swagger: '2.0'
info:
  version: 0.0.1
  title: Profile Manager
  description: User Profile Manager
basePath: /v1/profile
tags:
  - name: userProfileController
    description: User Profile Controller
paths:
  /:
    post:
      tags:
        - userProfileController
      summary: Create user profile
      description: Create user profile
      operationId: insertUserProfile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Details of the user profile to be created
          required: true
          schema:
            $ref: '#/definitions/Profile'
      responses:
        '201':
          description: Created
        '400':
          description: Invalid input supplied or Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  '/{username}':
    get:
      tags:
        - userProfileController
      summary: Get user profile
      description: Get user profile details
      operationId: getUserProfile
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: User's unique identifier
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Profile'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      tags:
        - userController
      summary: Update user
      description: Update user profile
      operationId: updateUserProfile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: User's unique identifier
          required: true
          type: string
        - name: body
          in: body
          description: Details of the user profile to be updated
          required: true
          schema:
            $ref: '#/definitions/Profile'
      responses:
        '204':
          description: OK
        '400':
          description: Invalid input supplied or Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - userController
      summary: Delete user
      description: Delete user profile
      operationId: deleteUserProfileByUsername
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: User's unique identifier
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
definitions:
  Profile:
    type: object
    properties:
      username:
        type: string
        description: User's unique identifier
      firstName:
        type: string
        description: First Name
      lastName:
        type: string
        description: Last Name
      dateOfBirth:
        type: string
        format: date
        description: Date of Birth
      addresses:
        type: array
        items:
          $ref: '#/definitions/ProfileAddress'
  ProfileAddress:
    type: object
    properties:
      line1:
        type: string
        description: Address Line 1
      line2:
        type: string
        description: Address Line 2
      town:
        type: string
        description: Town or City
      postalCode:
        type: string
        description: Postal Code
      region:
        type: string
        description: State or Province Name
      country:
        type: string
        description: Country Name
      addressType:
        $ref: '#/definitions/AddressType'
  AddressType:
    type: string
    description: Address Type
    enum:
      - home
      - office
